const $=s=>document.querySelector(s);
const path=('/'+location.pathname.slice(SITE_BASE.length)).replace(/\/index\.html$/,'').replace(/\/$/,'')||'/';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const telegram='https://t.me/+375291809009';
function header(){return `<header class="header wrap"><a class="logo" href="${SITE_BASE}">ваш<span>свет</span><small>салон светильников · минск</small></a><nav class="nav" id="navigation" aria-label="Основная навигация"><a href="${SITE_BASE}" ${path==='/'?'aria-current="page"':''}>Главная</a><a href="${SITE_BASE}catalog/" ${path==='/catalog'?'aria-current="page"':''}>Каталог</a><a href="${SITE_BASE}contacts/" ${path==='/contacts'?'aria-current="page"':''}>Контакты</a></nav><a class="admin-entry" href="${SITE_BASE}admin/">Демо админки ↗</a><button class="menu-toggle" aria-label="Открыть меню" aria-expanded="false" aria-controls="navigation">☰</button></header>`}
function footer(){return `<footer class="footer wrap"><div class="footer-main"><div><a class="logo" href="${SITE_BASE}">ваш<span>свет</span></a><p>Свет, с которым хорошо дома.</p></div><div class="footer-links"><a href="${SITE_BASE}catalog/">Каталог</a><a href="${SITE_BASE}contacts/">Контакты</a><a href="${telegram}" target="_blank" rel="noopener">Telegram ↗</a></div><div><a href="tel:+375291809009">+375 29 180-90-09</a><p>Минск, Уручская, 19 · павильон П81</p></div></div><div class="footer-bottom"><span>© ВашСвет</span><a href="${SITE_BASE}admin/">Управление каталогом ↗</a></div></footer>`}
function card(p){return `<a class="product-card" href="${SITE_BASE}product/?id=${p.id}"><div class="product-image"><img src="${esc(productImage(p))}" alt="${esc(p.name)}" loading="lazy" width="600" height="600"><span class="circle" aria-hidden="true">↗</span></div><div class="product-meta"><span>${esc(p.brand)}</span><span>${esc(p.category)}</span></div><h3>${esc(p.name)}</h3><p>${esc(productPrice(p))}</p></a>`}
function home(ps){return `<main class="fade"><section class="hero"><img src="${SITE_BASE}assets/hero.webp" alt="Концептуальный интерьер с тёплым светом скульптурной настольной лампы" width="1659" height="948" fetchpriority="high"><div class="hero-content"><span class="eyebrow">Свет для вашего пространства</span><h1>Дом начинается<br>с <span class="serif">тёплого</span><br>света.</h1><p>Выразительные формы. Мягкий свет.<br>Детали, которые меняют ощущение дома.</p><a class="button" href="${SITE_BASE}catalog/">Найти свой свет <span>↗</span></a></div><div class="hero-bottom"><span>Салон светильников в Минске</span><span>Интерьерная концепция</span></div></section><section class="section wrap"><div class="section-head"><div><span class="eyebrow">Знакомство с коллекцией</span><h2>Свет как часть интерьера</h2></div><a class="text-link" href="${SITE_BASE}catalog/">Смотреть каталог ↗</a></div><div class="grid">${ps.slice(0,3).map(card).join('')}</div></section><section class="quiet"><div class="section wrap statement"><div><span class="eyebrow">ВашСвет · персональный выбор</span><h2>Не просто освещать.<br><span class="serif">Создавать настроение.</span></h2></div><div class="statement-side"><p>Свет над обеденным столом. Лампа для вечернего чтения. Акцент, который объединяет интерьер.</p><p>Расскажите, какой свет вы ищете. Обсудим модели, наличие и детали заказа напрямую.</p><a class="text-link" href="${telegram}" target="_blank" rel="noopener">Обсудить подбор в Telegram ↗</a></div></div></section></main>`}
function catalog(ps){return `<main class="wrap fade"><div class="page-head"><div class="breadcrumbs"><a href="${SITE_BASE}">Главная</a><span>/</span><span>Каталог</span></div><span class="eyebrow">Форма. Материал. Свет.</span><h1>Найдите <span class="serif">свой свет.</span></h1><p>Для небольших деталей и больших перемен в интерьере.</p></div><div class="filters" aria-label="Категории каталога"><button class="filter active" data-category="all" aria-pressed="true">Все светильники</button>${[...new Set(ps.map(p=>p.category))].map(c=>`<button class="filter" data-category="${esc(c)}" aria-pressed="false">${esc(c)}</button>`).join('')}</div><section class="catalog-section"><p class="catalog-count" aria-live="polite">Моделей: ${ps.length}</p><div class="grid" id="products">${ps.map(card).join('')}</div></section></main>`}
function detail(ps){let p=ps.find(p=>p.id===new URLSearchParams(location.search).get('id'));if(!p)return `<main class="notfound"><h1>Модель не найдена</h1><p>Выберите светильник в демонстрационном каталоге.</p><a class="text-link" href="${SITE_BASE}catalog/">Вернуться в каталог</a></main>`;document.title=p.name+' — ВашСвет';return `<main class="wrap fade"><div class="page-head"><div class="breadcrumbs"><a href="${SITE_BASE}">Главная</a><span>/</span><a href="${SITE_BASE}catalog/">Каталог</a><span>/</span><span>${esc(p.name)}</span></div></div><section class="detail"><div class="product-image"><img src="${esc(productImage(p))}" alt="${esc(p.name)}" width="800" height="800"></div><div class="detail-info"><span class="eyebrow">${esc(p.brand || "ВашСвет")} · ${esc(p.category)}</span><h1>${esc(p.name)}</h1><p>${esc(p.description || "Рассмотрите модель и обсудите с менеджером, как она подойдёт вашему интерьеру.")}</p><dl class="details-list"><div><dt>Производитель</dt><dd>${esc(p.brand || "—")}</dd></div><div><dt>Категория</dt><dd>${esc(p.category)}</dd></div><div><dt>Артикул</dt><dd>${esc(p.sku || "—")}</dd></div></dl><div class="price">${esc(productPrice(p))}</div><p class="order-note">Уточним актуальную стоимость, наличие и срок поставки перед оформлением заказа.</p><a class="button" href="${telegram}?text=${encodeURIComponent('Здравствуйте! Интересует '+p.name+' ('+p.sku+'). Подскажите стоимость и наличие.')}" target="_blank" rel="noopener">Заказать в Telegram <span>↗</span></a><p class="tiny">Откроется диалог с салоном. Сообщение отправляете вы.</p><a class="text-link" href="tel:+375291809009">Или позвоните: +375 29 180-90-09</a></div></section></main>`}
function contacts(){return `<main class="wrap fade"><div class="page-head"><div class="breadcrumbs"><a href="${SITE_BASE}">Главная</a><span>/</span><span>Контакты</span></div></div><section class="contact-layout"><div><span class="eyebrow">Давайте познакомимся</span><h1>Ваш свет.<br><span class="serif">В нашем салоне.</span></h1><div class="contact-list"><div class="contact-item"><span class="eyebrow">Приходите</span><h3>Минск, ул. Уручская, 19</h3><p>Павильон П81. Перед визитом уточните время работы по телефону.</p><a class="text-link" style="font-size:14px;display:inline-block;margin-top:18px" href="https://yandex.by/maps/?text=${encodeURIComponent('Минск Уручская 19 павильон П81 ВашСвет')}" target="_blank" rel="noopener">Открыть на карте ↗</a></div><div class="contact-item"><span class="eyebrow">Позвоните</span><a href="tel:+375291809009">+375 29 180-90-09</a><p><a style="font-size:16px" href="tel:+375293999009">+375 29 399-90-09</a></p></div><div class="contact-item"><span class="eyebrow">Напишите</span><a href="mailto:molis_lux@mail.ru">molis_lux@mail.ru</a><p><a class="button" style="font-size:14px" href="${telegram}" target="_blank" rel="noopener">Связаться в Telegram ↗</a></p></div></div></div><div class="contact-visual"><img src="${SITE_BASE}assets/hero.webp" alt="Интерьерная визуальная концепция со скульптурной лампой"><div class="contact-caption"><span class="eyebrow">От идеи — к подходящему свету</span><h3>Начнём с вашего интерьера.</h3><p style="margin-top:15px">Отправьте фото комнаты или понравившуюся модель в Telegram.</p></div></div></section></main>`}
async function init(){let ps;try{const r=await fetch(SITE_BASE+'products.json');if(!r.ok)throw Error();ps=await r.json()}catch{document.getElementById('app').innerHTML=header()+`<main class="notfound"><h1>Не удалось загрузить каталог</h1><p>Обновите страницу или свяжитесь с салоном.</p><a href="${SITE_BASE}contacts/">Контакты</a></main>`+footer();return}
window.catalogSeed=ps;const all=CatalogStore.merge(ps);ps=all.filter(p=>p.status!=='draft');
if(path==='/admin'){document.title='Управление каталогом — ВашСвет';startAdmin(all);return}
if(path==='/proposal'){location.replace(SITE_BASE);return}
const render=path==='/'?home(ps):path==='/catalog'?catalog(ps):path==='/product'?detail(ps):path==='/contacts'?contacts():`<main class="notfound"><h1>Страница не найдена</h1><a href="${SITE_BASE}">На главную</a></main>`;
document.getElementById('app').innerHTML=header()+render+footer();if(path==='/catalog')document.title='Каталог светильников — ВашСвет';if(path==='/contacts')document.title='Контакты салона — ВашСвет';
$('.menu-toggle').addEventListener('click',e=>{const open=$('.nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open));e.currentTarget.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');e.currentTarget.textContent=open?'×':'☰'});
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});const result=b.dataset.category==='all'?ps:ps.filter(x=>x.category===b.dataset.category);$('#products').innerHTML=result.map(card).join('');$('.catalog-count').textContent='Моделей: '+result.length}));
const product=ps.find(p=>p.id===new URLSearchParams(location.search).get('id'));if(path==='/product' && product?.photos?.length>1){const main=$('.detail .product-image');const thumbs=document.createElement('div');thumbs.className='gallery-thumbs';thumbs.innerHTML=product.photos.map((src,i)=>`<button type="button" aria-label="Фото ${i+1}" aria-pressed="${i===0}" data-photo="${i}"><img src="${esc(src)}" alt=""></button>`).join('');main.append(thumbs);thumbs.querySelectorAll('button').forEach(b=>b.onclick=()=>{main.querySelector('img').src=product.photos[Number(b.dataset.photo)];thumbs.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))})}
}init();
